name       : nginx-unit
version    : 1.7
release    : 2
source     :
    - https://github.com/nginx/unit/archive/1.7.tar.gz : 7e750d4ae8ed96c0501da302c32e1bf0c2e66944f7a3bf249f3e187b7af8da7b
license    : Apache-2.0
component  : programming.tools
summary    : NGINX Unit is a dynamic web and application server
description: |
    NGINX Unit is a dynamic web and application server, designed to run applications in multiple languages.
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(python-3.6)
    - golang
    - ruby-devel
setup      : |
    ./configure --bindir=/usr/bin \
                --sbindir=/usr/sbin \
                --libdir=%libdir% \
                --incdir=/usr/include \
                --modules=%libdir%/nginx-unit \
                --state=/var/lib/nginx-unit \
                --log=/var/log/nginx-unit \
                --control=unix:/run/control.unit.sock \
                --user=unit \
                --group=unit \
                --openssl
    ./configure go --go-path=%libdir%/golang
    ./configure perl
    ./configure python --config=python3-config
    ./configure ruby
build      : |
    %make
install    : |
    %make_install
    rm -R $installdir/var
    install -Dm00644 $pkgfiles/nginx-unit.service $installdir/%libdir%/systemd/system/nginx-unit.service
    install -Dm00644 $pkgfiles/nginx-unit.sysusers $installdir/%libdir%/sysusers.d/nginx-unit.conf
    install -Dm00644 $pkgfiles/nginx-unit.tmpfiles $installdir/%libdir%/tmpfiles.d/nginx-unit.conf
    install -Dm00644 $pkgfiles/nginx-unit.default $installdir/usr/share/defaults/nginx-unit
patterns   :
    - go :
        - /usr/lib64/golang
    - perl :
        - /usr/lib64/nginx-unit/perl*
    - python :
        - /usr/lib64/nginx-unit/python*
    - ruby :
        - /usr/lib64/nginx-unit/ruby*
