name       : nginx-unit
version    : 1.24.0
release    : 12
source     :
    - https://github.com/nginx/unit/archive/refs/tags/1.24.0.tar.gz : da3926b650b32e3fbb4fad26f8b389fb762841bdcfd734626467d64a86587a66
homepage   : https://unit.nginx.org/
license    : Apache-2.0
component  :
    - programming.tools
    - go : programming.tools
    - perl : programming.tools
    - python : programming.tools
    - ruby : programming.tools
summary    : NGINX Unit is a dynamic web and application server
description: |
    NGINX Unit is a dynamic web and application server, designed to run applications in multiple languages.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(ruby-3.0)
    - golang
patterns   :
    - go :
        - /usr/lib64/golang
    - perl :
        - /usr/lib64/nginx-unit/perl*
    - python :
        - /usr/lib64/nginx-unit/python*
    - ruby :
        - /usr/lib64/nginx-unit/ruby*
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-Go-adding-main-configure-CFLAGS-and-LDFLAGS-t.patch
    ./configure --bindir=/usr/bin \
                --sbindir=/usr/sbin \
                --libdir=%libdir% \
                --incdir=/usr/include \
                --modules=%libdir%/nginx-unit \
                --state=/var/lib/nginx-unit \
                --log=/var/log/nginx-unit \
                --control=unix:/run/control.unit.sock \
                --user=unit \
                --group=unit \
                --openssl
    ./configure go --go-path=%libdir%/golang
    ./configure perl
    ./configure python --config=python3-config
    ./configure ruby
build      : |
    %make
install    : |
    %make_install
    rm -R $installdir/var
    install -Dm00644 $pkgfiles/nginx-unit.service $installdir/%libdir%/systemd/system/nginx-unit.service
    install -Dm00644 $pkgfiles/nginx-unit.sysusers $installdir/%libdir%/sysusers.d/nginx-unit.conf
    install -Dm00644 $pkgfiles/nginx-unit.tmpfiles $installdir/%libdir%/tmpfiles.d/nginx-unit.conf
    install -Dm00644 $pkgfiles/nginx-unit.default $installdir/usr/share/defaults/nginx-unit
